name: widgetbook_for_widgetbook
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  widgetbook_annotation: ^3.0.0-beta.4
  widgetbook: ^3.0.0-beta.8
  flutter_bloc: ^8.1.1
  widgetbook_core:
    path: ../packages/widgetbook_core

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
  widgetbook_generator: ^3.0.0-beta.8
flutter:
  uses-material-design: true